const routes = {
    home: '/',
    loginAdmin: '/admin/login',
    historyAdmin: '/admin/history',
    personnelManage: '/admin/personnel-manage',
    serviceManage: '/admin/service-manage',
    handOver: '/admin/hand-over',
    handOverManage: '/admin/hand-over-manage',
    customerManage: '/admin/customer-manage',
    nationality: '/admin/nationality',
    searchRoom: '/room/search',
    room: '/room/detail',
    chart: '/admin/chart',
    roomManage: '/admin/room-manage',
    floorManage: '/admin/floor-manage',
    createRoomManage: '/admin/create-room',
    createOptionRoomManage: '/admin/create-option-room',
    rentalTypeManage: '/admin/rental-type-manage',
    authorization: '/admin/authorization',
    login: '/login',
    signup: '/signup',
    notfound: '/*',
    roomPlan: '/admin/room-plan',
    kindOfRoom: '/admin/kind-of-room',
    rentalManageDetail: '/admin/rental-manage/:type/:idRoomChoose',
    rentalManageCheckIn: '/admin/rental-manage/:type/:idRoomChoose/:dateCheckIn/:dateCheckOut',
    bookingData: '/booking/:hireDate/:checkOutDay/:idKindOfRoom/:numberOfAdults/:numberOfKids/:quantityRoom/:quantityDay',
    bookingNoData: '/booking/:idKindOfRoom',
    bookingmanage: '/admin/booking-manage',
    manageBooking: '/admin/manage-booking',
    facilityManage: '/admin/facility-manage',
    bookingSuccess: '/:idBooking',
    kindOfRoomVer2: '/admin/kind-of-room-ver2',
    createKindOfRoom: '/admin/kind-of-room/:type',
    detailKindOfRoom: '/admin/kind-of-room/:type/:idKindOfRoom'
};
export default routes;
